server {
    listen 80;
    server_name localhost;

    location = /healthcheck {
        access_log off;
        default_type text/plain;
        return 200 OK\n;
    }

    location = /robots.txt {
        if ($host ~* "\.dl6") {
            add_header Content-Type text/plain;
            return 200 "User-agent: *\nDisallow: /\n";
        }
        try_files $uri =404;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
